### ISSUE TITLE
Join the beanstalkd github organization?

### ISSUE THREAD

**Issue by petri** [beanstalkd/beanstalk4py#1]
Hello,

I like this client you wrote. We recently moved another Python beanstalkd client (pybeanstalk) to the [github beanstalkd organization](https://github.com/beanstalkd), where quite a few other beanstalk clients are already hosted.

Would you like to join the beanstalkd github organization & transfer your client there as well? That would perhaps be a nice way to get more attention to it and help other Python users of beanstalkd.

**Comment by vit1251** [comment]
I agree, but I now was using AMQP based protocols for my work purposes.
So I don't use this Python module in the work. But I can answer question
about that.

**Comment by petri** [comment]
Thanks for responding. I understand. Will you transfer your beanstalk Python module to the beanstalk github organization then? It's easy to do from within your github repository 'settings'.

**Comment by petri** [comment]
@vit1251, what's the license for this Python module, by the way?

**Comment by vit1251** [comment]
@petri I would like to have reference as the author of the original module for all kinds of uses that module

**Comment by vit1251** [comment]
> Will you transfer your beanstalk Python module to the beanstalk github organization then?

@petri I have no success when try to transfer b4py to b organization. There GitHUB have restriction and ask about Admin right or organization. Could you call me by skype or some another way to instant message.

**Comment by petri** [comment]
@vit1251 of course you will be referenced as the original author. I did not realize github would put some restrictions on this. I asked @kr if he can help with the transfer.

**Comment by vit1251** [comment]
@petri OK. You may contact me by skype when you ready. I live in the Europe time zone GMT+0300.

**Comment by kr** [comment]
I can add @vit1251 to the org, and I think that should allow this repo to be transferred.

**Comment by petri** [comment]
@vit1251 so the transfer should work now?

**Comment by vit1251** [comment]
@kr @petri i try to do that

![image](https://cloud.githubusercontent.com/assets/110534/8696082/12dac7ec-2af2-11e5-87d2-98cb3ccdde7d.png)

and this require admin rights!

**Comment by vit1251** [comment]
Also I can not have permission to create repository

![image](https://cloud.githubusercontent.com/assets/110534/8696125/7628c330-2af2-11e5-847f-e9d5f94cf857.png)

And I don't know how to do that. We can write to GitHUB support for this deal ;-)

**Comment by kr** [comment]
Sorry, I added you to the wrong team. Please try one more time to transfer the repo.

**Comment by vit1251** [comment]
@kr migration is done. Remember that this is only a prototype.
